version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/symfony
      - ./logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/symfony
    container_name: ${PROJECT_NAME}-fpm
    links:
      - mysql
  npm:
    build:
      context: ./docker/npm
    volumes:
      - ./:/symfony
    container_name: ${PROJECT_NAME}-npm

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/symfony
    container_name: ${PROJECT_NAME}-cli
    links:
      - mysql
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: ${PROJECT_NAME}-pma
    links:
      - mysql:mysql
    ports:
      - "8002:80"
    environment:
      - "PMA_HOST=mysql"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}-mysql
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql: