front:
    resource: ../../src/Controller/
    type: annotation
admin:
    resource: ../../src/Controller/Admin/
    prefix: '/api'
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
