admin:
    resource: ../../src/Admin/Controller/
    type: annotation

front:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
