FROM php:7.4-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    wget \
    zlib1g-dev \
    libmcrypt-dev \
    libzip-dev \
    libpng-dev

RUN docker-php-ext-install pdo pdo_mysql gd

WORKDIR /parse.tor